WebApplication2/Models/Post.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication2.Models
{
    public class Post
    {
        [Key]
        [HiddenInput(DisplayValue = false)]
        public int PostID { get; set; }
        [Required]
        public string Title { get; set; }
        public string Image { get; set; }
        [Required]
        public int SumComment { get; set; }
        [Required]
        public string Content { get; set; }
        [Required, DataType(DataType.Date)]
        public DateTime DatePost { get; set; }
        [Required,DataType(DataType.EmailAddress)]
        public string UserName { get; set; }
        public int CategoryID { get; set; }
        public virtual Category Category { get; set; }
    }
}

WebApplication2/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class CommentController : Controller
    {
        private readonly ApplicationDbContext _db;
        private int postid = PostController._postid;
        public CommentController(ApplicationDbContext db)
        {
            _db = db;
        }
        [HttpGet]
        public IActionResult Create()
        {
            return RedirectToAction("Detail", "Post", new { @id = postid });
        }
        [Authorize]
        [HttpPost]
        public IActionResult Create(string status)
        {
            if(status!=null)
            {
                Comment comm = new Comment
                {
                    UserName = User.FindFirstValue(ClaimTypes.Name),
                    DateCom = DateTime.Now,
                    Content=status,
                    PostID=postid
                };
                var post = _db.Posts.Find(postid);
                post.SumComment++;
                _db.Entry(post).State= EntityState.Modified;
                _db.Comments.Add(comm);
                _db.SaveChanges();
            }
            return RedirectToAction("Detail", "Post", new { @id = postid });
        }
    }
}

WebApplication2/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Threading.Tasks;
using LazZiya.ImageResize;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private ApplicationDbContext _db;
        public static int _postid = 0;
        public PostController(ApplicationDbContext db)
        {
            _db = db;
        }
        [HttpGet]
        public IActionResult Create()
        {
            var data = _db.Categories.ToList();
            var list = new SelectList(data, "CategoryID", "CategoryName");
            ViewBag.ListCategory = list;
            ViewBag.Username = User.FindFirstValue(ClaimTypes.Name);
            return View();
        }
        [HttpPost]
        public IActionResult Create(Post entity)
        {
            if(!ModelState.IsValid)
            {
                return View(entity);
            }
            else
            {
                if (Request.Form.Files.Count != 0)
                {
                    var file = Request.Form.Files[0];
                    var filename = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');
                    string path = Path.Combine("wwwroot/Images/", filename);
                    
                    using (var fs = new FileStream(path, FileMode.Create))
                    {
                        if (file.Length > 0)
                        {
                            using (var str = file.OpenReadStream())
                            {
                                var presentImage = Image.FromStream(str);
                                if (presentImage.Width>600)
                                {
                                    var resizeImage = ImageResize.ScaleByWidth(presentImage, 300);
                                    resizeImage.Save(fs, ImageFormat.Jpeg);
                                }
                                else
                                    file.CopyTo(fs);
                            }
                        }
                    }
                    
                    entity.Image = filename;
                }
                entity.SumComment = 0;
                entity.DatePost = DateTime.Now;
                _db.Posts.Add(entity);
                _db.SaveChanges();
                return RedirectToAction("Index", "ManagerPost", null);
            }
        }
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Detail(int id)
        {
            var post = _db.Posts.Find(id);
            if (post == null)
            {
                ModelState.AddModelError("","Not found");
                return View();
            }
            _postid = id;
            ViewBag.Date = post.DatePost.ToShortDateString();
            ViewData["listcomm"] = _db.Comments.Where(x=>x.PostID==id).OrderByDescending(x=>x.CommentID).ToList();
            return View(post);

        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var edit = _db.Posts.Find(id);
            if (edit == null)
                return NotFound();
            else
            {
                var data = _db.Categories.ToList();
                var list = new SelectList(data, "CategoryID", "CategoryName");
                ViewBag.ListCategory = list;
                ViewBag.Username = User.FindFirstValue(ClaimTypes.Name);
                return View(edit);
            }
            
        }
        [HttpPost]
        public IActionResult Edit(Post edit)
        {
            if (!ModelState.IsValid)
            {
                return View(edit);
            }
            else
            {
                var data = _db.Posts.Find(edit.PostID);
                if (Request.Form.Files.Count!=0)
                {
                    
                    var file = Request.Form.Files[0];
                    var filename = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');
                    string path = Path.Combine("wwwroot/Images/", filename);
                    if (data.Image != null)
                    {
                        System.IO.File.Delete(path);
                    }
                    var stream = new FileStream(path, FileMode.Create);
                    if (file.Length > 0)
                    {
                        using (var str = file.OpenReadStream())
                        {
                            var presentImage = Image.FromStream(str);
                            if (presentImage.Width > 600)
                            {
                                //file.CopyTo(stream);
                                var resizeImage = ImageResize.ScaleByWidth(presentImage,300);
                                resizeImage.Save(stream, ImageFormat.Jpeg);
                            }
                            else
                                file.CopyTo(stream);
                        }
                    }
                    data.Image = filename;
                    
                }
                else
                {
                    data.Image = "";
                }
                data.Title = edit.Title;
                data.Content = edit.Content;
                data.DatePost = DateTime.Now;
                _db.Entry(data).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index", "ManagerPost", null);
            }
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var delete = _db.Posts.Find(id);
            if (delete == null)
                return NotFound();
            else
            {
                if (delete.Image != null)
                {
                    string path = Path.Combine("wwwroot/Images/", delete.Image);
                    System.IO.File.Delete(path);
                }
                _db.Posts.Remove(delete);
                _db.SaveChanges();
                return RedirectToAction("Index", "ManagerPost", null);
            }
        }
       
    }
}

WebApplication2/Views/Post/Create.cshtml
@model WebApplication2.Models.Post;
@{
    ViewData["Title"] = "Create";
}
@ViewBag.test
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                @Html.Hidden("UserName",@ViewBag.Username,null)

            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <p>Image:</p>
            <div class="form-group custom-file">
                <label asp-for="Image" class="control-label custom-file-label">Choose file</label>
                <input asp-for="Image" class="form-control custom-file-input" type="file" />
                <span asp-validation-for="Image" class="form-control-file"></span>
            </div>

            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CategoryID" class="control-label"></label>
                <p>
                    @Html.DropDownList("CategoryID", (SelectList)ViewBag.ListCategory, "--Select one--", new { style = "width:200px;" })
                    <span asp-validation-for="CategoryID" class="text-danger"></span>
                </p>

            </div>
            <div class="form-group">
                <input type="submit" value="Post" class="btn btn-primary" />
            </div>
        </form>
    </div>

</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts{
    <script>
        $(".custom-file-input").on("change", function () {
            var Image = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(Image);
        });
    </script>
}

WebApplication2/Views/Post/Detail.cshtml
@model WebApplication2.Models.Post

@{
    ViewData["Title"] = "Detail";
}

<h1>Detail</h1>
<style>
    body{margin-top:20px;}

.comment-wrapper .panel-body {
    max-height:650px;
    overflow:auto;
}

.comment-wrapper .media-list .media img {
    width:64px;
    height:64px;
    border:2px solid #e5e7e8;
    margin-right:10px;
}

.comment-wrapper .media-list .media {
    border-bottom:1px dashed #efefef;
    margin-bottom:25px;
}
                                    
</style>
<div class="posts">
    <p>
        <h6>@Model.UserName - @Model.DatePost.ToShortDateString()</h6>
    </p>

    <p>
        <h2><a asp-action="Detail" asp-controller="Post" asp-route-id="@Model.PostID">@Model.Title</a></h2>
    </p>
    <img src="~/Images/@Model.Image" class="offset-sm-1" />
    <h4 class="offset-sm-1">@Model.Content</h4>
    <h6 class="offset-sm-1">@Model.SumComment Comment</h6>
    <div id="comment">
        <div class="row bootstrap snippets">
            <div class="col-md-6 col-md-offset-2 col-sm-12">
                <div class="comment-wrapper">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            Comment
                        </div>
                        <div class="panel-body">
                            <form method="post" asp-action="Create" asp-controller="Comment">
                               
                                <textarea class="form-control" placeholder="write a comment..." rows="3" name="status"></textarea>
                                <br>
                                <input type="submit" value="Submit" class="btn btn-success"/>
                            </form>
                            
                            <div class="clearfix"></div>
                            <hr>
                            <ul class="media-list">
                                @foreach (var item in (List<Comment>)ViewData["listcomm"])
                                {
                                    <li class="media">
                                        <a href="#" class="pull-left">
                                            <img src="~/Images/avatar_2x.png" alt="" class="img-circle">
                                        </a>
                                        <div class="media-body">
                                            <span class="text-muted pull-right">
                                                @{TimeSpan time = DateTime.Now - item.DateCom;
                                                    int days = time.Days;
                                                    int hours = time.Hours;
                                                    int minutes = time.Minutes;
                                                    if (days > 0)
                                                    {
                                                        <small class="text-muted">@days day ago</small>
                                                    }
                                                    else
                                                    {
                                                        if (hours > 0)
                                                        {
                                                            <small class="text-muted">@hours hours @minutes minutes ago</small>
                                                        }
                                                        else
                                                        {
                                            <small class="text-muted">@minutes minutes ago</small>
                                                        }
                                                    }
                                                }

                                            </span><br />
                                            <strong class="text-success">@item.UserName</strong>
                                            <p class="offset-sm-1">
                                               @item.Content
                                            </p>
                                        </div>
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

WebApplication2/Views/Post/Edit.cshtml
@model WebApplication2.Models.Post

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Post</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PostID" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group custom-file">
                <label asp-for="Image" class="control-label custom-file-label">Choose file</label>
                <input asp-for="Image" class="form-control custom-file-input" type="file" value="@Model.Image" />
                <span asp-validation-for="Image" class="form-control-file"></span>
            </div>

            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CategoryID" class="control-label"></label>
                <p>
                    @Html.DropDownList("CategoryID", (SelectList)ViewBag.ListCategory, "--Select one--", new { style = "width:200px;" })
                    <span asp-validation-for="CategoryID" class="text-danger"></span>
                </p>
            </div>
            <div class="form-group">
                @Html.Hidden("SumComment", Model.SumComment, null)
            </div>
            <div class="form-group">
                @Html.Hidden("UserName", Model.UserName, null)
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts{
    <script>
        $(".custom-file-input").on("change", function () {
            var Image = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(Image);
        });
    </script>
}